### ISSUE TITLE
Next.js normalize.css error

### ISSUE THREAD

**Issue by greeksolid** [cerebral/classy-ui#18]
I get this error after upgrading to beta.

```
./node_modules/classy-ui/normalize.css
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js.
Read more: https://err.sh/next.js/css-global
Location: pages\classy.tsx
```

Is there a way to configure the plugin not to import normalize.css automatically?

**Comment by christianalfoni** [comment]
This is now fixed in latest `beta`, please read the install guide again for more information 😄

**Comment by greeksolid** [comment]
Will do. Thanks a lot Christian!!
