### ISSUE TITLE
NextJS Build Error

### ISSUE THREAD

**Issue by yovanoc** [cerebral/classy-ui#19]
```
Failed to compile.

./components/FirstComponent.tsx
Module not found: Can't resolve 'classy-ui/normalize.css' in '/Users/devchris/Documents/code/nodejs/project/packages/next/components'
```

I follow the new updated documentation :/

**Comment by christianalfoni** [comment]
Hi @yovanoc, 

We have made a new release now, could you try again please? 😄 Thanks for trying out the beta!

**Comment by yovanoc** [comment]
Yay! It works! But without going further, the Head thing have to be in every pages so?

**Comment by christianalfoni** [comment]
@yovanoc Oh, yeah... I believe we can change the docs to take advantage of the `_app` file, get back to you on this 😄

**Comment by yovanoc** [comment]
Thanks a lot! because i've spent a lot of time trying to make a boilerplate for nextjs with overmind and classy-ui :(

**Comment by christianalfoni** [comment]
Hi there!

So updated docs now :) https://classy-ui.io/install/next-js
