### ISSUE TITLE
Dynamic composition with typed destructured arguments

### ISSUE THREAD

**Issue by masqita** [cerebral/classy-ui#22]
Example:

```ts
const Button = ({ disabled }: { disabled?: boolean }) => (
  <button
    disabled={disabled}
    className={compose(disabled && tokens.color.GRAY_400)}
  ></button>
);

const Buttons = () => (
  <div>
    <Button></Button>
    <Button disabled></Button>
    <Button disabled={true}></Button>
    <Button disabled={false}></Button>
  <div/>
);
```

Because of the `&&` condition, falsy values are returned immediately instead of a token, leading to the following type error:

Type 'undefined/false' is not assignable to type 'IDecorators | "GROUP" | Themes | "CLASSNAME"'

**Comment by christianalfoni** [comment]
Hi @masqita , nice catch!

I have updated boolean to be allowed type in compose now on latest beta :)
