### ISSUE TITLE
Support Tailwind v1.2.0 release

### ISSUE THREAD

**Issue by deadcoder0904** [cerebral/classy-ui#8]
So last night Adam released [v1.2.0](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.2.0) & would love to have it supported :)

Thank you for this awesome library, it’s great not having to visit documentation again & again lol 😂

**Comment by christianalfoni** [comment]
Hi there!

In the latest video I talk about that we wanted to shift to being a "CSS property name" based approach, as it results in less mental overhead. We assume that you typically think of a CSS property you want to apply. With TailwindCSS you have to then translate that into what classname that CSS property is controlled by. In `classy-ui` you just think of the CSS property and it will be a classname 😄 

Also this is something we need to do for specificity reason.

Let me know if you feel something is missing and thanks for the feedback! 👍
